Restructured Emittance base data storage
e0404/matRad pull request #470
Opened 2020-12-15 10:46 UTC by pamede

I restructured the MCEmittanceBaseData class, such that it now stores the generated emittance base data, which can be used in a MCsquare or TOPAS Monte Carlo simulation, in a new fields in the matRad base data file. 
If one selects to create a new base data file, whichs should include the generated parametrisation, for every energy in the base data file, a field energySpectrum is now created, which contains the mean energy of the respective proton source and its energy spread. 
In addition, every initFocus field is expanded by the found beam optics data for every available focus index.
I also fixed smaller bugs related to the whole base data generation process in MCsquareBaseData.

2021-09-13 09:19 UTC, wahln requested changes
Almost integration-ready! Some minor comments though.

2021-09-13 09:19 UTC, wahln commented on MatRad_MCemittanceBaseData.m
> +                    tmp = energyData;
I don't really understand this & the following loop. Is there no other way to concatenate the structs?

2021-09-13 09:19 UTC, wahln commented on matRad_calcParticleDoseMCsquare.m
> +% MCsquareBDL = MCsquareBDL.saveMatradMachine('savedMatRadMachine');
Is it possible to remove some of the comments here that are not necessary?

One more idea: We could automatically save a mat-file with the emittance if it is automatically approximated (along with an appropriate mesesage that we approximated the phase space and that the machine is saved into a matfile which could have a name like, e.g., modality_machineName_lastMCApproximation. What do you think?

2021-12-02 15:12 UTC, closed without merging

2021-12-02 15:29 UTC, pamede commented
Moved code to PR [532](https://github.com/e0404/matRad/pull/532).