Small changes to where penalties are applied
e0404/matRad pull request #624
Opened 2023-05-26 14:16 UTC by tobiasbecher

Moved the penalties from the objectives to the objective function. Also added an option for objective constraint.

2023-06-05 08:09 UTC, amitantony commented on optimization/+DoseConstraints/matRad_ObjectiveConstraint.m
> +            obj@DoseConstraints.matRad_DoseConstraint(inputStruct);
for readability i would change this 'obj' named instance to something else, 'doseConstraint'

2023-06-21 10:58 UTC, wahln requested changes
Looks good, just have some minor comments. Thanks!

2023-06-21 10:58 UTC, wahln commented on optimization/+DoseConstraints/matRad_ObjectiveConstraint.m
> +classdef matRad_ObjectiveConstraint < DoseConstraints.matRad_DoseConstraint
I find the name a little ambiguous. Could we maybe switch to matRad_DoseConstraintFromObjective?

2023-06-21 10:58 UTC, wahln commented on optimization/+DoseConstraints/matRad_ObjectiveConstraint.m
> +        epsilon = 1e-3; %
The epsilon is the slip factor? Maybe rename or comment it.
Does it make sense to have the f^max as a named parameter (in the parameter system) and the epsilon/slip not? shold both be just class properties / is there any scenario where using it from the GUI sensible?

2023-06-21 10:58 UTC, wahln commented on optimization/+DoseObjectives/matRad_DoseObjective.m
> +        function constr = convertToConstraint(obj,maxObj,epsilon)
See my comment about "obj" and "constr" before. Really name it "objective" here.

2023-06-21 10:58 UTC, wahln commented on optimization/+DoseObjectives/matRad_DoseObjective.m
> +        function constr = convertToConstraint(obj,maxObj,epsilon)
And why is this function in the objective? Couldn't I just pass the Objective to, for example, the constructor of the ObjectiveConstraint directly? Why do I need it?

2023-06-21 10:58 UTC, wahln commented on optimization/+DoseObjectives/matRad_MaxDVH.m
> +            fDoseGrad = 2 * (1/numel(dose))*deviation;
2/numel(dose) ?

2023-07-21 13:09 UTC, merged