Dev pareto obj
e0404/matRad pull request #648
Opened 2023-07-21 13:40 UTC by tobiasbecher

2023-07-28 10:55 UTC, tobiasbecher reviewed
There are some changes related to normalization of objectives, that are not relevant for this part, but for the sandwich algorithms. Let me know, if I should move that to a seperate pull request

2023-09-01 13:58 UTC, wahln requested changes
Looks good, I am still not convinced that everything is done given the state of a few files.
Another comment: if we have an objectiveFunctions file that stores objective values as array, why do we not have a objectiveJacobian?

2023-09-01 13:58 UTC, wahln commented on matRad_fluenceOptimization.m
> +optiProb = matRad_OptimizationProblem(backProjection,cst);
See comment in the OptimizationProblem file!

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_OptimizationProblem.m
> +        normalizationScheme = struct('type','none');
What does "type" stand for? Not very instructive

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_OptimizationProblem.m
> +        objidx;
would adhere to coding style by using capital I: objIdx, constrIdx

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_OptimizationProblem.m
> +        function obj = matRad_OptimizationProblem(backProjection,cst)
I am not sure if we should add the cst as a parameter (compatibility to other stuff).
We could also generate this cache the first time we need it instead?

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_OptimizationProblem.m
> +        function obj = matRad_OptimizationProblem(backProjection,cst)
But actually I am not sure what's the best strategy here.... maybe leave it like this.

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_constraintJacobian.m
> +      %Iterate through columns of the sub-jacobian
Didn't you want to move this to the projections or was this other work?

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_objectiveFunction.m
> +            fIndv = optiProb.normalizeObjectives(fIndv')';%ISSUES IF COWC is used -
Are these issues solved?

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_objectiveFunction.m
> +            fIndv = optiProb.normalizeObjectives(fIndv')';%ISSUES IF COWC is used -
And what issues?

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_objectiveFunction.m
> +    %TODO: sum up over scenarios
What's with this TODO?

2023-09-01 13:58 UTC, wahln commented on optimization/@matRad_OptimizationProblem/matRad_objectiveFunction.m
This file seems to be not very finalized, maybe clarify the comments and if something is still debatable.

2023-11-03 10:25 UTC, closed without merging

2023-11-03 10:26 UTC, tobiasbecher commented
Closed due to changes being added in other pull request