Load incomplete matrad structure set and consistent warning and error handling
e0404/matRad pull request #673
Opened 2023-11-14 15:29 UTC by amitantony

1. checks ct, cst, pln , result GUI and matRad GUI can load an incomplete matRad structure set 
2. update widgets in try catch blocks 
3. warnings and errors handled using the matRad_Widget function showWarning / showError

2023-11-14 15:39 UTC, amitantony commented
replaces the previous PR #668

2023-11-16 09:27 UTC, wahln requested changes

2023-11-16 09:27 UTC, wahln commented on gui/matRad_Widget.m
> +        function this = doUpdate(this)
Should probably be doUpdate(this,~) to be consistent in number of accepted arguments?

2023-11-16 16:19 UTC, wahln approved these changes

2023-11-17 11:58 UTC, merged