Dev varRBE robopt world coordinate system
e0404/matRad pull request #751
Opened 2024-07-22 15:37 UTC by amitantony

This PR should replace the old world coordinate system PR #704

2024-07-22 15:42 UTC, amitantony commented
comments for reviewers
1. Ive checked the examples run through , please let me know if there are new parts of code not covered in the examples that ive missed
2. would appreciate Reviewers with more MC experience to test out those parts of the code, results for Example 12 were quite close to that of the clean dev varRBErobOpt but Im unsure of how close, close should be 
cheers 🍻

2024-07-23 08:35 UTC, wahln commented
Can you quickly write a summary about
- the different coordinates system now used and where there (default) origin is? I see the world system, which probably is given by ct.x/y/z and is defaulted like it was before.  And I see the cube system which uses the i,j,k and translates directly to coordinates.
- Which entities are living in which coordinate system? Isocenter always in world? doseGrid.x/y/z also in world? When is the cube system used (only internal functions)?
- Maybe it would make sense to already consider the orientation of the system kn the functions somehow. Such that in the future, we could also transform easily between different medical systems / anatomical orientations.

2024-07-23 09:03 UTC, wahln requested changes
Good work, but I think some stuff could be a bit cleaner. Also, there seems to be some regular transformations which could deserve their own functions and are not directly clear why they are done this way (maybe add comments).

2024-07-23 09:03 UTC, wahln commented on matRad/plotting/matRad_plotAxisLabels.m
> +
See other comments

2024-07-23 09:03 UTC, wahln commented on matRad/tools/matRad_generateSingleBixelStf.m
>  end
See other comments

2024-07-23 09:03 UTC, wahln commented on matRad/tools/matRad_generateSingleBixelStf.m
> +% zVox = ct.resolution.z*[1:ct.cubeDim(3)]-ct.resolution.z/2;
If this is no longer needed, let's delete it

2024-07-23 09:03 UTC, wahln commented on matRad/tools/matRad_generateSingleBixelStf.m
> +    shiftedIsoCenter = vertcat(stf(:).isoCenter) - [ct.x(1) ct.y(1) ct.z(1)] + [ct.resolution.x ct.resolution.y ct.resolution.z] ;
Again this annoying transformation

2024-07-24 09:29 UTC, amitantony commented on matRad/geometry/matRad_world2cubeCoords.m
> +function coord = matRad_world2cubeCoords(wCoord, ct)
Ive set up a way for us to either pass the ct or dij.doseGrid or the dij.ctGrid. does this make sense ?

2024-07-24 09:40 UTC, wahln commented on matRad/geometry/matRad_world2cubeCoords.m
> +function coord = matRad_world2cubeCoords(wCoord, ct)
Yes. I think that the ctGrid and doseGrid in the dij look quite similar. They also have a .resolution.x/y/z and potentially an .x/y/z with the plan coordinates. The difference to the ct is that ct has "cubeDim" while the grids have "dimensions".

2024-07-24 09:43 UTC, amitantony commented on matRad/geometry/matRad_projectOnComponents.m
> +% This file is not part of the offical matRad release ?
was a personal note, my bad. 
why is this not part of the official release ?

2024-07-24 11:15 UTC, amitantony commented
Summary of the different coordinate systems :
1. voxel coordinates ( i, j, k) in cube
used for all handling within the cube and GUI 

2. world coordinates (x, y, z) [mm]
where the isocenter is defined, therefore consistent with all dicom patient positioning 

3. raytracing coordinates, same as world but shifted so that isocenter is at origin (x, y, z)
this is used by raytracing and all the dosecalc Functions

2024-07-24 11:19 UTC, amitantony commented on matRad/matRad_generateStf.m
> +        coordsZ = wCoords(:,3) - pln.propStf.isoCenter(i,3);
didnt want to change the coordsX /Y/Z notation, if i change that then its one line

2024-07-24 13:51 UTC, wahln commented on matRad/geometry/matRad_projectOnComponents.m
> +% This file is not part of the offical matRad release ?
This line should be removed and the whole section should be replaced with the standard message.

2024-07-24 13:53 UTC, wahln commented on matRad/matRad_generateStf.m
> +        coordsZ = wCoords(:,3) - pln.propStf.isoCenter(i,3);
If we don't need the coords(X/Y/Z) separately further down, it is good to make a one-liner out of this.

2024-07-24 15:17 UTC, JenHardt commented
> comments for reviewers
> 
> 1. Ive checked the examples run through , please let me know if there are new parts of code not covered in the examples that ive missed
> 2. would appreciate Reviewers with more MC experience to test out those parts of the code, results for Example 12 were quite close to that of the clean dev varRBErobOpt but Im unsure of how close, close should be
>    cheers 🍻

i think from a MC point of view you are good to go

2024-07-25 14:50 UTC, wahln commented
Also there's a huge number of tests failing:
https://github.com/e0404/matRad/actions/runs/10060022215
Unfortunately currently printingthe failures do not work on all PRs, but it will as soon as the new pipeline is on the master-branch.

2024-07-27 22:52 UTC, wahln approved these changes
Looks good now!
However, I wonder how you manually tested the alignment of the grids? Just by looking at the dosimetric results (equivalence) or did you debug and check that similar values are generated?

2024-08-07 17:22 UTC, wahln approved these changes

2024-08-07 17:22 UTC, wahln commented
Will take a look on why the tests don't run through.

2024-08-07 17:23 UTC, wahln commented
> Will take a look on why the tests don't run through.

My bad, it's only the failing coverage report in PRs.

2024-08-07 17:23 UTC, merged