class based biological models
e0404/matRad pull request #756
Opened 2024-08-09 13:52 UTC by remocristoforetti

Class based structure for biological modelling.

2024-08-29 15:20 UTC, amitantony commented on matRad/bioModels/BioModels/LQbasedModels/LETbasedModels/RBEminMaxModels/matRad_Wedemberg.m
> +classdef matRad_Wedemberg < matRad_RBEminMax
I believe its spelt Wedenberg with the N

2024-10-10 11:44 UTC, wahln requested changes
Preliminary review for now while this is still under construction

2024-10-10 11:44 UTC, wahln commented on matRad/bioModels/LQbasedModels/RBEtabulatedModels/matRad_LQRBETabulatedModel.m
> +        % end
This can probably be safely deleted?

2024-10-10 11:44 UTC, wahln commented on matRad/bioModels/LQbasedModels/RBEtabulatedModels/matRad_TabulatedSpecralKernelBasedModel.m
> +
What about this comment block?

2024-10-10 11:44 UTC, wahln commented on matRad/gui/widgets/matRad_ViewingWidget.m
> +                            otherwise
What about BED?

2024-10-10 11:44 UTC, wahln commented on matRad/matRad_version.m
I think it was not good to take the RC branch as a reference because now the version is messed up. After the review we should rebase and discard the version change.

2024-10-10 11:44 UTC, wahln commented on matRad/util/matRad_getStructFieldsAndSubfields.m
> +% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
The double %%% line is inconsistent with the rest of matRad

2024-10-10 11:44 UTC, wahln commented on matRad/util/matRad_getSubfolders.m
> +% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
see above

2024-10-10 11:44 UTC, wahln commented on matRad/util/matRad_getSubfolders.m
I think that this function is somewhat overcomplicated. You can just use Matlab's `genpath` and then split the returned path string by pathsep.

2024-10-16 21:37 UTC, wahln approved these changes

2024-10-16 22:01 UTC, merged